baseURL = "https://fairese.com/"
languageCode = "en-us"
title = "Fairese"
theme = "tailbliss"

[params]
moto = "From compliance to creativity."
description = "Fairese is a one-man software consultancy led by Sergio Andrés Ibañez Kautsch (known professionally as Andy Ibanez), an iOS developer with a background in aviation, banking, and fintech. He delivers reliable, high-quality software without the overhead of a big agency, and is the author of Modern Concurrency on Apple Platforms."
author = "Sergio Andrés Ibañez Kautsch"

[params.p1]
heading = "How I Work"
image = "images/pages/how-i-work.png"

[[params.p1.content]]
text = "Every project I take on is guided by two forces: precision and imagination. My background in aviation, banking, and fintech has trained me to think in terms of systems, safety, and structure — but I believe the best software also needs clarity, warmth, and purpose."

[[params.p1.content]]
text = "I don’t build disposable code or rush toward MVPs. I build things to last — tools that solve real problems cleanly and scale with calm confidence."

[[params.p1.content]]
text = "I work closely with clients, not as a vendor, but as a technical partner. That means thoughtful scoping, honest communication, and careful execution from the first commit to the final handoff."

[[params.p1.content]]
text = "Whether it’s an internal platform or a public-facing app, my goal is the same: to deliver software that feels quietly exceptional — well-architected, elegantly implemented, and easy to live with."

[[params.p1.content]]
text = "I work with AI, not against it — but I don’t confuse automation with authorship. When you hire me, you’re not getting a prompt engineer. You’re getting a partner who knows when to trust the machine — and when to override it."

[[params.p1.content]]
text = "If that sounds like the kind of collaboration you're looking for — let’s talk."

[params.p2]
heading = "Why Fairese Works For You"
image = "images/pages/hacktoberfest.jpg"

[[params.p2.content]]
text = "I'm aligned with U.S. time zones, operate from Bolivia, and speak fluent English. I bring the clarity of a senior engineer — without the layers of a big firm. You'll work directly with me: no project managers, no account executives, just fast, honest collaboration with someone who actually ships."

[[params.p2.content]]
text = "I adapt to your workflow, not the other way around. Whether you use GitHub, Notion, Jira, or something else entirely — I integrate seamlessly and keep communication tight. Need async updates? Daily standups? Weekly demos? Done."

[[params.p2.content]]
text = "I take pride in delivering code that’s readable, tested, and production-ready. But I also know when to move fast and simplify. I don’t pad estimates."

[[params.p2.content]]
text = "You’re not just hiring someone to code — you’re hiring someone who will think with you. I challenge assumptions, surface edge cases, and bring creative clarity to the messiest ideas. That’s why clients trust me with core systems and long-term work."

[params.p3]
heading = "Clients who trust my code"

[[params.p3.content]]
text = "I’ve helped mission-critical teams across industries — from aviation to banking — build the software they depend on every day. Whether it’s internal tools or production systems, my work supports high-stakes operations with clarity and reliability."

[[params.p3.links]]
text = "Meet the teams I’ve supported"
url = "#"

[[params.p3.logos]]
identifier = "a"
image = "images/global/sample-logo.svg"
alt = "a"

[[params.p3.logos]]
identifier = "b"

[[params.p3.logos]]
identifier = "c"

[[params.p3.logos]]
identifier = "d"

[[params.p3.logos]]
identifier = "e"

[[params.p3.logos]]
identifier = "f"